version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: EcommerceDB
    ports:
      - "5432:5432"
    volumes:
      - ./product.sql:/docker-entrypoint-initdb.d/product.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "3000:3000"
    environment:
      PGUSER: postgres
      PGHOST: db
      PGDATABASE: EcommerceDB
      PGPASSWORD: password1234
      PGPORT: 5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: "http://localhost:3000"

volumes:
  postgres_data:
